import turtle
import math
sizeofstar=input("enter size of star")
wn=turtle.Screen()
wn.bgcolor("white")
jim=turtle.Turtle()
jim.color("black")
jim.pd()
jim.right(162)
jim.forward((0.5*int(sizeofstar))/math.sin(math.radians(72)))
jim.left(162)
jim.pd()
jim.color("red")
jim.begin_fill()
jim.forward(int(sizeofstar))
jim.left(144)
jim.forward(int(sizeofstar))
jim.left(144)
jim.forward(int(sizeofstar))
jim.left(144)
jim.forward(int(sizeofstar))
jim.left(144)
jim.forward(int(sizeofstar))
jim.left(144)
jim.end_fill()
jim.ht()
wn.exitonclick()