import postage3
import postage2
import postage1
print('testing of first figure')
print('correct value is 0.49')
print(postage1.postage(0.9))
print('correct value is 0.49')
print(postage1.postage(1))
print('correct value is 0.71')
print(postage1.postage(1.1))
print('correct value is 1.15')
print(postage1.postage(3.5))
print('correct value is 1.64')
print(postage1.postage(3.6))
print('correct value is 2.96')
print(postage1.postage(10))
print('')
print('testing of second figure')
print('correct value is 0.49')
print(postage2.postage(0.9))
print('correct value is 0.49')
print(postage2.postage(1))
print('correct value is 0.71')
print(postage2.postage(1.1))
print('correct value is 1.15')
print(postage2.postage(3.5))
print('correct value is 1.64')
print(postage2.postage(3.6))
print('correct value is 2.96')
print(postage2.postage(10))
print('')
print('testing of third figure')
print('correct value is 0.49')
print(postage3.postage(0.9))
print('correct value is 0.49')
print(postage3.postage(1))
print('correct value is 0.71')
print(postage3.postage(1.1))
print('correct value is 1.15')
print(postage3.postage(3.5))
print('correct value is 1.64')
print(postage3.postage(3.6))
print('correct value is 2.96')
print(postage3.postage(10))