totalsize=int(input('enter total desired size in pixels: '))
increment=int(input('what step size (in pixels) between turns? '))
import turtle
import math
wn=turtle.Screen()
alex=turtle.Turtle()
#alex.fillcolor('red')
#alex.begin_fill()
for n in range(0,totalsize,increment):
    alex.pu()
    alex.forward(n/increment)
    alex.pd()
    alex.forward(n/increment)
    alex.pu()
    alex.forward(n/increment)
    alex.pd()
    alex.forward(n/increment)    
    alex.pu()
    alex.forward(n/increment)
    alex.pd()
    alex.forward(n/increment)
    alex.pu()
    alex.forward(n/increment)
    alex.pd()
    alex.forward(n/increment)
    alex.pu()
    alex.forward(n/increment)
    alex.pd()
    alex.forward(n/increment) 
    alex.left(90)
#alex.end_fill()
wn.exitonclick()